### ISSUE TITLE
set navbar bg for pkgdown website to nutriverse green

### ISSUE THREAD

**Issue by ernestguevarra** [nutriverse/mwana#136]
add this to `_pkgdown.yml`:

```yaml
template:
  bootstrap: 5
  theme: breeze-light
  ganalytics: ""
  bslib:
    bootswatch: pulse
    pkgdown-nav-height: 100px
    success: "#004225"

navbar:
  bg: success
  type: dark
```

note that #004225 is nutriverse green (aka british racing green)

This will match what we are now using for the nutriverse website
